language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - DB=mysql

matrix:
  exclude:
    - php: hhvm
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - mysql -e "create database IF NOT EXISTS graphite_test;";

script:
  - phpunit tests